import { Flex, Box, Center } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Home1 from "../public/Images/Home1.jpg";

const Home: NextPage = () => {
  return (
    <Flex
      as={Box}
      width="100%"
      height="100%"
      bg="#fff"
      justifyContent="center"
      flexDirection="column"
    >
      <Head>
        <title>Sharpsharp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Box mt={['50px',  '100px', '200px']}>
          <Image src={Home1} alt="home page image" width={1200} height={700} />
        </Box>
        <Flex>

        </Flex>
      </Center>
    </Flex>
  );
};

export default Home;
