import { Flex, Box, Center } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import {ProductPage} from '../Component/ProductPage/Electronics'
import Home1 from "../public/Images/Home1.jpg";
import Image from "next/image";
import ReactTypingEffect from 'react-typing-effect';
import { ClassNames } from "@emotion/react";
import styles from '../styles/Home.module.css';
import { Kitchen } from "../Component/ProductPage/Kitchen";
import { Grocery } from "../Component/ProductPage/Grocery";
const Home: NextPage = () => {
  return (
    <Flex
      as={Box}
      width="100%"
      height="100%"
      bg="#fff"
      justifyContent="center"
      flexDirection="column"
      background='#fff9fb'
    >
      <Head>
        <title>Sharpsharp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Center>
     
   <Flex flexDir='column'>
   <Center>
   <Box fontSize='20px' fontWeight='500' width='50%' backgroundColor='#20A39E' color='white' height='30px' padding='7px' mt={['50px',  '80px', '100px']}>
      <ReactTypingEffect
        className={styles.Typed}
        text={["All our Products are on payment on delivery plan", "We will not ask you to pay online","We will not call to ask for your bank details", "Please Do not give your bank details to anyone", "Do not Pay Online", "Pay On Delivery"]}
      />
      </Box >
   </Center>
   <Box mt='10px'>
      <Image src={Home1} alt="home page image" width={1200} height={700} />
    </Box>
    <Center>
      <Flex flexDir='column'>
    <ProductPage/>
    <Kitchen/>
    <Grocery/>
    </Flex>
    </Center>
   </Flex>
     </Center>
    </Flex>
  );
};

export default Home;
